version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Contraseña obtenida desde .env
      POSTGRES_DB: ${DB_NAME} # Nombre de bd obtenida desde .env
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data #Ligar los datos de la bd a una carpeta física en el proyecto
